{{- if and .Values.postgresql.enabled .Values.postgresql.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "job-tracker.fullname" . }}-postgresql
  labels:
    {{- include "job-tracker.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.postgresql.password }}
{{- end }}
